config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  namespace :users do
    get :dashboard
    get :search
    post :request_access
    post :approve_access
  end
  root to: 'users#dashboard'
  resources :prescriptions
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  belongs_to :users_role, class_name: "Users::Role"
  has_many :prescriptions

  has_many :subscriber_subscribes, -> { where status: Subscribe::INACTIVE_STATUS }, foreign_key: :subscription_id, class_name: "Subscribe" 
  has_many :subscribers, through: :subscriber_subscribes, source: :subscriber

  has_many :subscription_subcribes, -> { where status: Subscribe::ACTIVE_STATUS }, foreign_key: :subscriber_id, class_name: "Subscribe"    
  has_many :subscriptions, through: :subscription_subcribes, source: :subscription


  before_validation :generate_uuid, on: :create, presence: true, uniqueness: true

  accepts_nested_attributes_for :prescriptions, allow_destroy: true

  USER_ROLE_ID_SEARCH_MAP = {1 => [2,3], 2 => [1], 3 => [1]}

  def generate_uuid
    uuid = "#{(0...8).map { rand(9) }.join}"
    while ::User.find_by(uuid: uuid).present? do
      uuid = "#{(0...8).map { rand(9) }.join}"
    end
    self.uuid = uuid
  end

  def search(search)
    if search
      self.class.all.where(:users_role_id=>USER_ROLE_ID_SEARCH_MAP[self.users_role_id]).where('email ILIKE ? OR uuid ILIKE ?', "#{search}", "#{search}")
    else
      []
    end
  end
end

app/models/users.rb
module Users
  def self.table_name_prefix
  'users_'
  end
end  

app/models/users/role.rb
class ::Users::Role < ActiveRecord::Base
  has_one :user
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :set_current_user

  def search
    @search_results = @current_user.search(params[:q])
  end

  def dashboard
    @subscriptions = @current_user.subscriptions
    @subscribers = @current_user.subscribers
  end

  def request_access
    if params[:user_uuid].present?
      subscription_id = ::User.find_by_uuid(params[:user_uuid]).id
      subs = Subscribe.find_or_create_by(:subscription_id=>subscription_id, :subscriber_id=>@current_user.id)
      render :json => {:message => "Succsfuly submitted request. Please go to home page. We are building this page"}, status: 200
    else
        render :json => {:message => "invalid user uuid"}, status: 400
    end
  end

  def approve_access
     if params[:user_uuid].present?
      subscriber_id = ::User.find_by_uuid(params[:user_uuid]).id
      subs = Subscribe.where(:subscription_id=>@current_user.id, :subscriber_id=>subscriber_id).last
      subs.approve
      render :json => {:message => "Succsfuly approved access. Please go to home page. We are building this page"}, status: 200
    else
        render :json => {:message => "invalid user uuid"}, status: 400
    end 
  end

  def set_current_user
    @current_user = current_user
  end
end

app/views/users/_doctor_dashboard.html.erb
<h3>Your UUID<small>(Please share this id with your patient)</small>: <%=@current_user.uuid%></h3>

<%=render 'search_form'%>

<h5>Patients</h5>
<table class="table table-bordered table-stripped" style="width: 600px">
    <thead>
        <th>Patient Id</th>
        <th>Patient Name</th>
        <th>Prescription</th>
    </thead>
    <tbody>
        <%@subscriptions.each do |patient|%>
            <tr>
                <td><%=patient.uuid%></td>
                <td><%=patient.email%></td>
                <td>
                    <ul>
                        <%patient.prescriptions.each do |p|%>
                                <li><%=p.name%></li>
                                <li><%p.pharmeasy_files.each do |file|%>
                                        <img src="<%=file.file_name%>" style="height: 50px; float: left; margin-right: 5px"/>
                                    <%end%>
                                </li>
                        <%end%>
                    </ul>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

app/views/users/_doctor_search_results.html.erb
<table class="table table-bordered table-stripped" style="width: 600px">
    <thead>
        <th>Patient Id</th>
        <th>Patient Name</th>
        <th>Action</th>
    </thead>
    <tbody>
        <%@search_results.each do |patient|%>
            <tr>
                <td><%=patient.uuid%></td>
                <td><%=patient.email%></td>
                <td>
                <%= form_tag users_request_access_path do %>
                  <p>
                    <%= hidden_field_tag :user_uuid, patient.uuid %>
                    <%= submit_tag "Request Access", :name => nil %>
                  </p>
                <% end %>
            </tr>
        <%end%>
    </tbody>
</table>

app/views/users/_patient_dashboard.html.erb
<h3>Your UUID<small>(Please share this id with your doctor)</small>: <%=@current_user.uuid%></h3>

<h5>Past Prescriptions</h5>
<%= link_to('Add Prescription', new_prescription_path) %>
<table class="table table-bordered table-stripped" style="width: 300px">
    <thead>
        <th>Prescriptions</th>
        <th>Images</th>
    </thead>
    <tbody>
        <%@current_user.prescriptions.each do |p|%>
            <tr>
                <td><%=p.name%></td>
                <td><%p.pharmeasy_files.each do |file|%>
                        <img src="<%=file.file_name%>" style="height: 50px; float: left; margin-right: 5px"/>
                    <%end%>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

<h5>Access Request</h5>
<table class="table table-bordered table-stripped" style="width: 600px">
    <thead>
        <th>Requester Id</th>
        <th>Requester Email</th>
        <th>Request Type</th>
        <th>Action</th>
    </thead>
    <tbody>
        <%@subscribers.each do |req|%>
            <tr>
                <td><%=req.uuid%></td>
                <td><%=req.email%></td>
                <td><%=req.users_role.name%></td>
                <td>
                    <%= form_tag users_approve_access_path do %>
                      <p>
                        <%= hidden_field_tag :user_uuid, req.uuid %>
                        <%= submit_tag "Approve Access", :name => nil %>
                      </p>
                    <% end %>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

app/views/users/_search_form.html.erb
<%= form_tag users_search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :q, params[:q], placeholder: "Search Patients" %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/users/dashboard.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<%= render "#{@current_user.users_role.dashboard_prefix}dashboard"%>

app/views/users/search.html.erb
<%=render 'search_form'%>
<%= render "#{@current_user.users_role.dashboard_prefix}search_results"%>